import { useState } from 'react';
import Head from 'next/head';
import { Web3Storage } from 'web3.storage';
import styles from '../styles/Home.module.css';

const client = new Web3Storage({ token: process.env.NEXT_PUBLIC_WEB3_STORAGE_API_TOKEN });

export default function Home() {
  const [inputFiles, setInputFiles] = useState([]);
  const [logMessage, setLogMessage] = useState('');
  const [rootCid, setRootCid] = useState('');
  const [loading, setLoading] = useState(false);

  const handleFileUpload = async () => {
    if (inputFiles.length > 0) {
      setLoading(true);
      setLogMessage('Uploading files to Web3.Storage...');
      const rootCid = await client.put(inputFiles);
      setRootCid(rootCid);
      setLogMessage(`Uploaded ${inputFiles.length} files. Root CID: ${rootCid}`);
      setLoading(false);
    } else {
      setLogMessage('No files selected');
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Web3 Storage Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span>Web3.Storage</span>
        </h1>

        <p className={styles.description}>
          Upload files to IPFS using Web3.Storage
        </p>
        <div className={styles.mainContainer}>
          <label className={styles.label} htmlFor="inputFiles">Select files</label>
          <input className={styles.input} name="inputFiles" type="file" multiple onChange={(e) => setInputFiles(e.target.files)} />
          <button className={styles.button} onClick={handleFileUpload}>Upload</button>
        </div>
        {loading && <p>Loading...</p>}
        <p>{logMessage}</p>
        {rootCid && (
          <a href={`https://${rootCid}.ipfs.w3s.link`} target="_blank" rel="noopener noreferrer">View on IPFS</a>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/Salmandabbakuti"
          target="_blank"
          rel="noopener noreferrer"
        >
          © 2022 Salman Dabbakuti. Built with Lit Protocol
        </a>
      </footer>
    </div >
  );
}
